### ISSUE TITLE
duplicates tenants created 

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/apigateway#30] opened 2016-12-04 20:49 UTC
Run the docker container locally for example on host 

Do a http PUT http://192.168.99.100:9000/v1/tenants
```
{
    "instance": "openwhisk",
    "namespace": "whisk.system"
}
```
response is
```
{
  "instance": "openwhisk",
  "id": "b07770ab-8a63-4606-b3db-07186e4bb457",
  "namespace": "whisk.system"
}
```
Run the same PUT again, I get a different id/guid:

```
{
  "instance": "openwhisk",
  "id": "1c114db8-60b0-429b-b416-74220e7163c0",
  "namespace": "whisk.system"
}
```
This should not be the case

**Comment by alexsong93** [comment] 2016-12-04 21:00
@csantanapr Is this happening for the local gateway? I believe I fixed this issue in a previous commit, and I am unable to reproduce it. Try pulling down the latest version and see if you are still seeing this.

**Comment by lostinthestory** [comment] 2016-12-04 23:26
@csantanapr confirmed that this isn't present in `develop`. Closing this.

**Closed by lostinthestory** 2016-12-04 23:26 UTC
